---
- import_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "vars['amdcovc_install_package'] is defined"
  - "vars['amdcovc_install_package'] == true"
- include_tasks: deploy_amdcovc.yml
  when:
  - "vars['amdcovc_instance_settings'] is defined"
  - "vars['amdcovc_instance_settings'] != ''"
